# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workspacewizard.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.setWindowModality(QtCore.Qt.ApplicationModal)
        Wizard.resize(597, 457)
        Wizard.setWizardStyle(QtWidgets.QWizard.AeroStyle)
        self.welcome = QtWidgets.QWizardPage()
        self.welcome.setObjectName("welcome")
        Wizard.addPage(self.welcome)
        self.nameTypePage = QtWidgets.QWizardPage()
        self.nameTypePage.setObjectName("nameTypePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.nameTypePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.nameTypePage)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.nameTypePage)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nameEdit = QtWidgets.QLineEdit(self.nameTypePage)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_3 = QtWidgets.QLabel(self.nameTypePage)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.locationEdit = QtWidgets.QLineEdit(self.nameTypePage)
        self.locationEdit.setObjectName("locationEdit")
        self.horizontalLayout_2.addWidget(self.locationEdit)
        self.locationBrowse = QtWidgets.QPushButton(self.nameTypePage)
        self.locationBrowse.setObjectName("locationBrowse")
        self.horizontalLayout_2.addWidget(self.locationBrowse)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.editMode = QtWidgets.QRadioButton(self.nameTypePage)
        self.editMode.setObjectName("editMode")
        self.verticalLayout.addWidget(self.editMode)
        self.rpMode = QtWidgets.QRadioButton(self.nameTypePage)
        self.rpMode.setChecked(True)
        self.rpMode.setObjectName("rpMode")
        self.verticalLayout.addWidget(self.rpMode)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.label_4 = QtWidgets.QLabel(self.nameTypePage)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout_2.addLayout(self.formLayout)
        Wizard.addPage(self.nameTypePage)
        self.sourcesPage = QtWidgets.QWizardPage()
        self.sourcesPage.setSubTitle("")
        self.sourcesPage.setObjectName("sourcesPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sourcesPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.settingsList = QtWidgets.QListWidget(self.sourcesPage)
        self.settingsList.setObjectName("settingsList")
        self.horizontalLayout_4.addWidget(self.settingsList)
        self.settingsBox = QtWidgets.QGroupBox(self.sourcesPage)
        self.settingsBox.setObjectName("settingsBox")
        self.horizontalLayout_4.addWidget(self.settingsBox)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.sourcesPage)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.removeButton = QtWidgets.QPushButton(self.sourcesPage)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        self.addButton = QtWidgets.QPushButton(self.sourcesPage)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        Wizard.addPage(self.sourcesPage)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "New Workspace Wizard"))
        self.welcome.setTitle(_translate("Wizard", "Welcome to the New Workspace Wizard"))
        self.welcome.setSubTitle(_translate("Wizard", "Press Next to create your workspace"))
        self.nameTypePage.setTitle(_translate("Wizard", "Set Workspace Details"))
        self.label_5.setText(_translate("Wizard", "<html><head/><body><p>Please give your workspace a name, a path to save, and a type.</p><p><br/></p><p>If you want to make a resource pack, use resource pack mode to save changes to files. If you want</p><p>to directly edit files (like for creating mods), use Edit Mode.</p></body></html>"))
        self.label_2.setText(_translate("Wizard", "Workspace Name"))
        self.label_3.setText(_translate("Wizard", "Workspace Location"))
        self.locationBrowse.setText(_translate("Wizard", "..."))
        self.editMode.setText(_translate("Wizard", "Edit Mode"))
        self.rpMode.setText(_translate("Wizard", "Resource Pack Mode"))
        self.label_4.setText(_translate("Wizard", "Workspace Type"))
        self.sourcesPage.setTitle(_translate("Wizard", "Add Sources To Workspace"))
        self.settingsBox.setTitle(_translate("Wizard", "Source Settings"))
        self.label.setText(_translate("Wizard", "Use the buttons to add and remove sources. Edit sources on the right"))
        self.removeButton.setText(_translate("Wizard", "Delete source"))
        self.addButton.setText(_translate("Wizard", "Add source"))

